### ISSUE TITLE
Cache key warnings

### ISSUE THREAD

**Issue by sikmir** [arkanister/django-flickr-gallery#3]
```
django/core/cache/backends/base.py:244: CacheKeyWarning: Cache key contains characters that will cause errors if used with memcached: ":1:{'nojsoncallback': 1, 'photoset_id': '...', 'extras': 'description, url_o, url_s, url_q, url_t, url_m, url_n, url_-, url_z, url_c, url_b, url_h, url_k', 'user_id': '...', 'page': '7', 'format': 'json', 'per_page': 30, 'method': 'flickr.photosets.getPhotos'}"
  CacheKeyWarning)
```

[Django’s cache framework](https://docs.djangoproject.com/en/1.8/topics/cache/):

> Memcached, the most commonly-used production cache backend, does not allow cache keys longer than 250 characters or containing whitespace or control characters, and using such keys will cause an exception. To encourage cache-portable code and minimize unpleasant surprises, the other built-in cache backends issue a warning (django.core.cache.backends.base.CacheKeyWarning) if a key is used that would cause an error on memcached.

**Comment by arkanister** [comment]
Cache control in `models.py` has been disabled, the only available cache management is used from [flickrapi](https://pypi.python.org/pypi/flickrapi) library.
