### ISSUE TITLE
Add django-taggit integration

### ISSUE THREAD

**Issue by sikmir** [arkanister/django-flickr-gallery#8]
It would be nice to replace (or make it optional) existing categories implementation with [django-taggit](http://django-taggit.readthedocs.org/en/latest/index.html).
Initial work already done in my branch sikmir/django-flickr-gallery@03417005d8ea315d7a6190870ab09b4814f954aa. It's not ready for opening PR yet, but any constructive feedback is welcome.

**Comment by arkanister** [comment]
Hello sikmir,

The implementation of categories was used in only one project, so I made as simple as possible, but I really liked the integration with `django-taggit`. I think it is interesting to openness to new implementations. I appreciate the idea.

Please make a pull request with this implementation and will be available next tag.

Sorry about the delay, the end of the year was somewhat tiring for me.

Thanks again for contributing,

Kind regards.
